name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish crate
    strategy:
      matrix:
        include:
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
        # Two or more tags must be present to make an error.
        if: ${{ github.ref_name }} != '0.1.0'

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cargo-${{ matrix.os }}

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md
        if: ${{ github.ref_name }} != '0.1.0'
